---
title: Marine World Heritage Sites shapefiles
date: "`r Sys.Date()`"
author: Pieter Provoost
output: (function(...) {
  rmdformats::robobook(toc_depth = 4, pandoc_args = c("+RTS", "-K2000m", "-RTS"), ...) })
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs") })  
---

This brief notebook merges marine World Heritage Sites shapefiles from different sources to be used for querying OBIS

## Load spatial data

First fetch the Marine World Heritage Sites shapefile from MarineRegions:

```{css, echo=FALSE}
.page-inner {
  max-width: 1000px !important;
}
```

```{r message=FALSE, warning=FALSE}
library(sf)
library(dplyr)
library(mapview)
library(sfheaders)

if (!file.exists("data/shape/worldheritagemarineprogramme.shp")) {
  download.file("http://geo.vliz.be/geoserver/wfs?request=getfeature&service=wfs&version=1.0.0&typename=MarineRegions:worldheritagemarineprogramme&outputformat=SHAPE-ZIP", "data/shape.zip")
  unzip("data/shape.zip", exdir = "shape")
}

shapes_mr <- st_read("data/shape/worldheritagemarineprogramme.shp") %>%
  select(full_name, country, geometry) %>%
  mutate(full_name = iconv(full_name, "latin1", "UTF-8")) %>%
  mutate(geometry = st_make_valid(sf_remove_holes(geometry))) %>%
  group_by(full_name) %>%
  summarize(geometry = st_union(geometry)) %>%
  mutate(source = "MarineRegions")
```

Then load the shapefile provided by WHC.

```{r message=FALSE, warning=FALSE}
shapes_whc <- st_read("data/World_Heritage_Sites/World_Heritage_Sites.shp", options = "ENCODING=UTF-8") %>%
  filter(MARINE != "0") %>%
  select(full_name = NAME, country = ISO3, geometry) %>%
  mutate(geometry = st_make_valid(sf_remove_holes(geometry))) %>%
  group_by(full_name) %>%
  summarize(geometry = st_union(geometry)) %>%
  mutate(source = "WHC (marine)")

shapes_whc_notmarine <- st_read("data/World_Heritage_Sites/World_Heritage_Sites.shp", options = "ENCODING=UTF-8") %>%
  filter(MARINE == "0") %>%
  select(full_name = NAME, country = ISO3, geometry) %>%
  mutate(geometry = st_make_valid(sf_remove_holes(geometry))) %>%
  group_by(full_name) %>%
  summarize(geometry = st_union(geometry)) %>%
  mutate(source = "WHC (not marine)")
```

Make a map:

```{r message=FALSE, warning=FALSE}
mapviewOptions(legend.opacity = 0.5, fgb = FALSE)

mapview(bind_rows(shapes_mr, shapes_whc, shapes_whc_notmarine), zcol = "source", col.regions = c("#d95243", "#81b533", "#43b8d9"), lwd = 0.5, alpha = 1, alpha.regions = 0.5, layer.name = "Source")@map
```

## Merge

To do.